[package]
name = "tidb_query_common"
version = "0.0.1"
edition = "2018"
publish = false
description = "Common utility of a query engine to run TiDB pushed down executors"

[features]
default = ["protobuf-codec"]
protobuf-codec = [
  "error_code/protobuf-codec",
  "tikv_util/protobuf-codec",
]
prost-codec = [
  "error_code/prost-codec",
  "tikv_util/prost-codec",
]

[dependencies]
anyhow = "1.0"
time = "0.1"
derive_more = "0.99.3"
error_code = { path = "../error_code", default-features = false }
tikv_util = { path = "../tikv_util", default-features = false }
kvproto = { rev = "7a046020d1c091638e1e8aba623c8c1e8962219d", git = "https://github.com/pingcap/kvproto.git", default-features = false }
prometheus = { version = "0.12", features = ["nightly"] }
prometheus-static-metric = "0.5"
lazy_static = "1.3"
log_wrappers = { path = "../log_wrappers" }
thiserror = "1.0"

[dev-dependencies]
byteorder = "1.2"

