[package]
name = "engine_panic"
version = "0.0.1"
description = "An example TiKV storage engine that does nothing but panic"
edition = "2018"
publish = false

[features]
default = ["protobuf-codec"]
protobuf-codec = [
  "engine_traits/protobuf-codec",
  "kvproto/protobuf-codec",
  "raft/protobuf-codec",
  "tikv_util/protobuf-codec",
  "txn_types/protobuf-codec",
]
prost-codec = [
  "engine_traits/prost-codec",
  "kvproto/prost-codec",
  "raft/prost-codec",
  "tikv_util/prost-codec",
  "txn_types/prost-codec",
]

[dependencies]
engine_traits = { path = "../engine_traits", default-features = false }
tikv_alloc = { path = "../tikv_alloc" }
# FIXME: Remove this dep from the engine_traits interface
tikv_util = { path = "../tikv_util", default-features = false }
kvproto = { rev = "dda0a102bc6ac7371e1f99cd2797825aa210b4a0", git = "https://github.com/pingcap/kvproto.git", default-features = false }
raft = { version = "0.6.0-alpha", default-features = false }
txn_types = { path = "../txn_types", default-features = false }
